# Site settings
title: AWS Calculator Templates
description: > # this means to ignore newlines until "baseurl:"
  I couldn't find a list of AWS Calculator Templates anywhere to help me figure out how much different kinds of websites or applications would cost to host there. So I made this.
baseurl: "http://www.daraul.com/projects/" # the subpath of your site, e.g. /blog/
url: "AWSCalculatorTemplates/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
